### ISSUE TITLE
在脚手架中的 ts 文件依赖其他 ts 文件无效

### ISSUE THREAD

**Issue by buhe** [MMF-FE/wepy-template#1]
hey，Awesome project
在脚手架中的 ts 文件依赖其他 ts 文件无效
在term 中显示
[Error] 找不到文件: {some_path}/src/components/counter/other

请问你们有这种使用场景么？还是我哪里做错了？

**Comment by angrycans** [comment]
你的other 是other.ts   吗？ wepy的typescript 还不支持自动索引index.ts

**Comment by angrycans** [comment]
<script lang="TypeScript">

  import {Msg, MessageKey} from '../../kits/index'

这么去引用 

还有你使用1.6.1-alpha4 版本了吗

**Comment by ciwyaitd** [comment]
@buhe sorry，看官方源码，目前还不能单独编译独立的 .ts 文件，
~~@angrycans 期待官方后续更新一个 `wepy-plugin-typescript` 的 plugin。~~
官方在一个月前已经支持 import .ts 文件，更新一下 wepy 版本就好。

曾尝试使用如 `vue-property-decorator` 类似的方式，使用装饰器对类进行处理，
但不适合 wepy 的编译模式。这样的话，就不能很好地使用 IDE 工具了(名存实亡)。
所以后续会分享一个基于 gulp 工作流的，支持 typescript 的，使用原生写法的另一个项目模板。
