### ISSUE TITLE
demo编译报错

### ISSUE THREAD

**Issue by walter211** [MMF-FE/wepy-template#3]
[Error] 找不到文件: /Users/cw/huo/wepy-template/wx_nodebb/src/common/baseComponent.js
[Error] 找不到文件: /Users/cw/huo/wepy-template/wx_nodebb/src/common/baseComponent.js
[Error] 找不到文件: /Users/cw/huo/wepy-template/wx_nodebb/src/common/baseComponent.js
[Error] 找不到文件: /Users/cw/huo/wepy-template/wx_nodebb/src/common/baseComponent.js
[Error] 找不到文件: /Users/cw/huo/wepy-template/wx_nodebb/src/common/baseComponent.js
[Error] 找不到文件: /Users/cw/huo/wepy-template/wx_nodebb/src/common/base.js

**Comment by ciwyaitd** [comment]
不好意思，wepy.config.js 有改动
wepy.config.js 里面改一下就好，或者 pull 一下
`'page': path.join(__dirname, 'src/common/base.ts'),
            'component': path.join(__dirname, 'src/common/baseComponent.ts')`

**Comment by walter211** [comment]
好的，我看下

**Comment by walter211** [comment]
(unknown) thirdScriptError 
 sdk uncaught third Error 
 module "common/base.ts.js" is not defined 
 Error: module "common/base.ts.js" is not defined
    at require (http://127.0.0.1:60065/appservice/__dev__/WAService.js:15:18132)
    at http://127.0.0.1:60065/appservice/__dev__/WAService.js:15:17987
    at http://127.0.0.1:60065/appservice/pages/index/index.js:19:14
    at require (http://127.0.0.1:60065/appservice/__dev__/WAService.js:15:18238)
    at http://127.0.0.1:60065/appservice/appservice:1041:9
console.error
appservice:1044 Wed Mar 07 2018 09:45:01 GMT+0800 (CST) page 编译错误
(unknown) pages/index/index.js 出现脚本错误或者未正确调用 Page()
console.error

**Comment by walter211** [comment]
issue 可以先不要关吗，我把框架搞通没问题之后再close，至少保证demo上手没问题

**Comment by ciwyaitd** [comment]
@walter211 不是改成  base.ts.js

wepy.config.js 是改成：
`'page': path.join(__dirname, 'src/common/base.ts'),
 'component': path.join(__dirname, 'src/common/baseComponent.ts')`

**Comment by ciwyaitd** [comment]
@walter211 最新代码不会有报错，pull 一下，再 init 试试

**Comment by walter211** [comment]
我是改成你说的样子，但是编译出来不知道为什么自动加了'.js'

**Comment by walter211** [comment]
我上面复制的不是命令行报错，是控制台的error

**Comment by ciwyaitd** [comment]
@walter211 这个有可能与 wepy 版本有关。建议尝试最新代码

**Comment by walter211** [comment]
'@': path.join(__dirname, 'src'),
            'page': path.join(__dirname, 'src/common/base'),
            'component': path.join(__dirname, 'src/common/baseComponent')

**Comment by walter211** [comment]
用的最新1.7.1 改成这样控制台没错了，去掉ts
