### ISSUE TITLE
请问如何使用typescript的代码提示？

### ISSUE THREAD

**Issue by WangShuXian6** [MMF-FE/wepy-template#4]
tslint似乎没有发挥作用。

**Comment by ciwyaitd** [comment]
@WangShuXian6 这是你第一次使用 typescript 吗？还是只有这个项目的 typescript 不起作用呢？

**Comment by WangShuXian6** [comment]
用过一段时间的typescript了。

在eslint和tslint里面配置的规则没有约束效果，例如规则静止使用分号，但命令行和微信开发者工具编译后完全正常，没有提示任何错误。
例如在ts里对函数参数进行类型约束后，函数调用时给一个不符合约束规则的参数。命令行和微信开发者工具编译后也是完全正常，没有报错。这不符合规则。是不是我没找到错误提示的地方？

**Comment by hanwenbo** [comment]
在eslint和tslint里面配置的规则没有约束效果，例如规则静止使用分号，但命令行和微信开发者工具编译后完全正常，没有提示任何错误。
仅仅在编辑器里可以。。。。。。。。。。。。。 没意义

**Comment by ciwyaitd** [comment]
1. 目前这个项目用的是 typescript，所以 eslint 配置不适用于本项目；
2. 官方目前没有支持 tslint 的语法编译校验，所以没有报错提示等相关错误约束；
3. 目前语法错误只能通过编辑器提示和发现；
4. 不要忽略了 typescript 强大的强类型系统和超前的语言特性；
@hanwenbo

**Comment by hanwenbo** [comment]
@ciwyaitd 是的 所以这块基本没什么用  官方存在欺诈行为  为了推广，谢谢啊

**Comment by vfasky** [comment]
@hanwenbo 是的，欺诈你了，不好意思，麻烦离开这里

**Comment by hanwenbo** [comment]
@vfasky 我说的wepy  没和你说话 别硬贴着我
